feat(tests): create generalized and random mock dataclasses for backe…
SwEnt-Group13/Unio pull request #123
Opened 2024-10-31 18:34 UTC by Aurelien9Code

…nd tests (only at first)

This PR implements a Mock class in the tests for Associations, Events, Locations, Users, ReferenceLists for the backend tests.

2024-11-01 12:41 UTC, Zafouche reviewed
Great initiative @Aurelien9Code! Randomness can be both good to make sure every edge case is covered, however it could mean the CI passes one time while the other time, it doesn't, so that could cause problems.

2024-11-01 16:11 UTC, armouldr requested changes
Overall good addition to the project that's gonna facilitate testing and especially make the test clearer. However I think that you should make it easier for someone to get a non-random object from these "MockObject" classes, because for now creating a non-random object with your classes is the same as creating the object directly.

You should also change change the boolean value to true at line 85 of MockAssociation.kt as I believe this uses more memory than necessary.

To summarise, there's just some little arrangements to make and I'll approve your PR :)

2024-11-02 13:50 UTC, Aurelien9Code commented on app/src/test/java/com/android/unio/model/association/MockAssociation.kt
> +              MockUser.createAllMockUsers(associationDependency = false)
Yes you are right, it's just a minor error and I will change it to "true"

2024-11-02 13:54 UTC, Aurelien9Code commented on app/src/test/java/com/android/unio/model/association/MockAssociation.kt
> +    private fun getRandomUid(): String = "assoc${Random.nextInt(1000, 9999)}"
I didn't catch your sentence

2024-11-02 13:55 UTC, Aurelien9Code commented on app/src/test/java/com/android/unio/model/association/MockAssociation.kt
> +              "A space for tech enthusiasts to collaborate and innovate.")
I think then it would be better to do it inside a test calling my mock, and overwriting the description parameter ; )

2024-11-02 13:56 UTC, Aurelien9Code commented on app/src/test/java/com/android/unio/model/event/MockEvent.kt
> +        types: List<EventType> = listOf(getRandomEventType())
Good catch !

2024-11-02 14:14 UTC, Aurelien9Code commented on app/src/test/java/com/android/unio/model/firestore/MockReferenceList.kt
> +}
I think it's already done.. I don't see it

2024-11-02 17:26 UTC, armouldr submitted a review, later dismissed

2024-11-03 16:52 UTC, Aurelien9Code commented
Yes i didn't finish haha

2024-11-04 09:03 UTC, Aurelien9Code commented
Please check https://github.com/SwEnt-Group13/Unio/pull/123/#issue-2627568739

Sonar failing condition will be fixed in next big refactor of the tests

2024-11-05 14:28 UTC, armouldr approved these changes
Looks all good to me now ! Would be great to have more line coverage but I think it will increase as we incorporate your new mock methods into our tests :)

2024-11-05 20:22 UTC, merged